modLoader = "javafml"
loaderVersion = "[43,)"
license = "LGPLv3.0"

issueTrackerURL = "https://github.com/62832/Fullblock-Energistics/issues"
displayURL = "https://github.com/62832/Fullblock-Energistics"

[[mods]]
modId = "fulleng"
version = "${version}"
displayName = "Fullblock Energistics"
logoFile = "thanks_doc.png"
authors = "90"
description = "A more retrospective feel for AE2."

[[dependencies.fulleng]]
    modId = "ae2"
    mandatory = true
    versionRange = "[12.9.1,13.0.0)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.fulleng]]
    modId = "merequester"
    mandatory = false
    versionRange = "[1.0.2,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.fulleng]]
    modId = "forge"
    mandatory = true
    versionRange = "[43,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.fulleng]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,1.20)"
    ordering = "NONE"
    side = "BOTH"
