modLoader = "javafml"
loaderVersion = "[$loaderVersion,)"
license = "LGPLv3.0"

issueTrackerURL = "https://github.com/62832/Fullblock-Energistics/issues"
displayURL = "https://github.com/62832/Fullblock-Energistics"

[[mods]]
modId = "fulleng"
version = "$version"
displayName = "Fullblock Energistics"
logoFile = "thanks_doc.png"
authors = "90"
description = "A more retrospective feel for AE2."

[[dependencies.fulleng]]
    modId = "ae2"
    mandatory = true
    versionRange = "[$ae2Version,$ae2VersionEnd)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.fulleng]]
    modId = "merequester"
    mandatory = false
    versionRange = "[$requesterVersion,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.fulleng]]
    modId = "forge"
    mandatory = true
    versionRange = "[$loaderVersion,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.fulleng]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[$minecraftVersion]"
    ordering = "NONE"
    side = "BOTH"
