name: Build

on:
  pull_request:
    # Only on branches, not tags/releases
    branches: ["**"]
  push:
    branches: ["*"]
  release:
    types: [published]

permissions:
  contents: write

concurrency:
  group: ci-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Generate assets
        run: ./gradlew runData
      - name: Check that data was generated
        run: test -d ./src/generated/resources/.cache
      - name: Ensure generated data is up-to-date
        run: |
          git status
          if [ -n "$(git status --porcelain)" ]; then exit 1; fi
      - name: Build release files
        run: ./gradlew build
      - name: Publish release files
        if: ${{ github.event_name == 'release' }}
        uses: Kir-Antipov/mc-publish@995edadc13559a8b28d0b7e6571229f067ec7659
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

          curseforge-id: 776293
          curseforge-token: ${{ secrets.CURSEFORGE_API_KEY }}

          modrinth-id: 24BlI6Ao
          modrinth-token: ${{ secrets.MODRINTH_API_KEY }}

          game-versions: 1.21.1
          loaders: neoforge
          dependencies: |
            ae2(required){curseforge:223794}{modrinth:XxWD5pD3}
            merequester(optional){curseforge:688367}{modrinth:E6BFl96N}
            extendedae(optional){curseforge:892005}{modrinth:JiOqfoFM}
            appliede(optional){curseforge:1009940}{modrinth:SyKS54UY}
