name: Release
on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
      - name: Generate data
        run: ./gradlew downloadAssets runData --max-workers 1
      - name: Build release files
        env:
          FULLENG_VERSION: ${{ github.event.release.tag_name }}
        run: ./gradlew build --max-workers 1
      - name: Publish release files (Fabric)
        uses: Kir-Antipov/mc-publish@4db8bd126f74d5e143822181a2b1201308e2c796
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

          curseforge-id: 776293
          curseforge-token: ${{ secrets.CURSEFORGE_API_KEY }}

          modrinth-id: 24BlI6Ao
          modrinth-token: ${{ secrets.MODRINTH_API_KEY }}

          files: fabric/build/libs/*[0-9].jar
      - name: Publish release files (Forge)
        uses: Kir-Antipov/mc-publish@4db8bd126f74d5e143822181a2b1201308e2c796
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

          curseforge-id: 776293
          curseforge-token: ${{ secrets.CURSEFORGE_API_KEY }}

          modrinth-id: 24BlI6Ao
          modrinth-token: ${{ secrets.MODRINTH_API_KEY }}

          files: forge/build/libs/*[0-9].jar